# Generated by Django 4.0.6 on 2023-01-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('username', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
